import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navigation from '../components/navigation';
import { useEffect } from 'react';

let season = {
	Winter: [1, 2, 3],
	Spring: [4, 5, 6],
	Summer: [7, 8, 9],
	Fall: [10, 11, 12],
};

export default function Home() {
	let date = new Date();
	let currentYear, currentMonth;

	useEffect(() => {
		currentYear = date.getFullYear();
		currentMonth = date.getMonth() + 1;
		for (let i in season) {
			if (season[i].includes(currentMonth)) console.log(i);
		}
	});
	return (
		<div className={styles.container}>
			<Head>
				<title>Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Navigation />
			</main>
		</div>
	);
}
