import Head from 'next/head';
import styles from '../styles/Home.module.css';
import AnimeList from '../components/animelist';
import Filter from '../components/filter';
import axios from 'axios';

export default function Home({ myData }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>AnimeDB | Home</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Filter />
				<AnimeList myData={myData} />
			</main>
		</div>
	);
}

export const getStaticProps = async () => {
	try {
		const result = await axios.get(
			`https://api.jikan.moe/v4/seasons/now`
		);
		const data = result.data.data;
		return {
			props: {
				myData: data,
			},
		};
	} catch (error) {
		console.log(error);
	}
};
