import Head from 'next/head';

function Search() {
	return (
		<>
			<Head>
				<title>AnimeDB | Search</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Search</h1>
		</>
	);
}

export default Search;
