import Head from 'next/head';

function Seasonal() {
	return (
		<>
			<Head>
				<title>Seasonal</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</>
	);
}

export default Seasonal;
